# Generated by Django 4.2.20 on 2025-04-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avaible',
            new_name='is_available',
        ),
    ]
