# nginx.yml

version: '3.8'

services:
  nginx:
    image: nginx:latest
    # Mapea el puerto 80 del contenedor al puerto 80 de tu máquina.
    # Esta es la puerta de entrada pública a tu aplicación.
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Monta el archivo de configuración que creamos en el paso 1.
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Monta los volúmenes compartidos para que Nginx pueda leer los archivos.
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
      - static_volume:/app/static:ro
      - ./media:/app/media:ro
    networks:
      - neura_django
    # Asegura que Nginx no intente iniciarse antes que la aplicación Django.
#    depends_on:
#      - web

volumes:
  static_volume:
  media_volume:

networks:
  neura_django:
    external: true