# web.yml (Versión para el servidor/producción)

version: '3.8'

services:
  web:
    # Le decimos a Docker que use esta imagen específica del registro
    image: ghcr.io/jornkbz/ecommerce-django:latest

    # Política de "pull": asegura que siempre intente descargar la última versión
    pull_policy: always

    # Los volúmenes y el archivo .env se mantienen igual
    volumes:
      - ./media:/app/media
      - static_volume:/app/static
    env_file:
      - .env

    # La configuración de red y dependencias también se mantiene
    networks:
      - neura_django
#    depends_on:
#      - db

#volumes:
#  media_volume:
#  static_volume:
volumes:
  # Definición principal del volumen
  static_volume:
    name: shared_static_volume # <-- Le damos un nombre explícito y global

networks:
  neura_django:
    external: true