# Generated by Django 4.2.20 on 2025-05-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
