# Generated by Django 4.2.23 on 2025-08-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderproduct_color_remove_orderproduct_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='payments',
            new_name='payment',
        ),
    ]
